### ISSUE TITLE
How to use DataClamp protocol?

### ISSUE THREAD

**Issue by kostaNew** [MichaelClerx/myokit#251]
Hello, I am exploring myokit to determine its possibilities and restrictions. 

I found the following information into changelog:

> **Version 1.25.0**
> Added data-clamp to CVODE simulation (works, but generally a bad idea). 

How can I perform a data-clamp simulation with myokit? Why is this a bad idea?

**Comment by MichaelClerx** [comment]
Hi!

The relevant method is [Simulation.set_fixed_form_protocol(times, voltages)](https://myokit.readthedocs.io/api_simulations/Simulation.html#myokit.Simulation.set_fixed_form_protocol). I have used this myself to apply pre-calculated AP waveforms to ion current models.

The reasons I'd advise against using it for other cases are:

1. Because the lists contain sampled points, it's easy to lose a bit of accuracy. For example if the points are spread evenly with some time step dt, the maximum upstroke will be ~140/dt. This is is not a big problem but means you need to be more careful than when using a full cell model to determine the AP.

2. When using the event-based pacing system (by given the simulation a [Protocol](https://myokit.readthedocs.io/api_simulations/Protocol.html) object), the simulator knows exactly where any discontinuities are and will force the solver to visit those points exactly. When encoding short stimuli (i.e. for current-clamp on whole cell models) in other ways, for example with data clamp or by using if-statements in the model (like CellML imports do), the variable step size solver doesn't have this knowledge, and could step over a stimulus completely. Again this can be avoided if you're careful, but it's better not to use data clamp for situations you can handle with a Protocol.

Hope that helps!

**Comment by MichaelClerx** [comment]
Did that help at all, @kostaNew ?
