### ISSUE TITLE
QT, multiple guis: "Portal: open file is ready"

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/myokit#677]
On latest fedora, dialogs are not always displayed immediatly (esp. in GDE, but in IDE too after plotting)

**Comment by MichaelClerx** [comment]
Not sure where to start... https://stackoverflow.com/questions/65795100

**Comment by MichaelClerx** [comment]
Happens in Veusz too, so not restricted to Myokit.

**Comment by MichaelClerx** [comment]
Goes away when switching back from X to Wayland

**Comment by MichaelClerx** [comment]
No idea if there's a workaround, seems only to happen on X on latest fedora, so probably a bit too cutting edgy :-(

**Comment by dchristopherfennell** [comment]
Hello,

This is the only post I founds that has what I've experience after installing Rocky 8 and qtcreator 8.0.2.

When I File->Open File or Project, I get a window that says "Portal: "Open File" is ready", instead of a file browser that opens up in the directory of the current file (xdg-open %d).

Did you find a solution to your problem?

**Comment by MichaelClerx** [comment]
Sorry @dchristopherfennell , it seems to have just gone away. Now on Gnome 44.10 where it works fine both with X11 and with Wayland.
